<?php
/**
 * QuotesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers and prospect data manipulation
 *
 * OpenAPI spec version: 1.5.0
 * Contact: it@getsirena.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * QuotesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuotesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getProspectQuotes
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Quotes
     */
    public function getProspectQuotes($prospect_id, $format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        list($response) = $this->getProspectQuotesWithHttpInfo($prospect_id, $format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after);
        return $response;
    }

    /**
     * Operation getProspectQuotesWithHttpInfo
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Quotes, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProspectQuotesWithHttpInfo($prospect_id, $format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        $returnType = '\Swagger\Client\Model\Quotes';
        $request = $this->getProspectQuotesRequest($prospect_id, $format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Quotes',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProspectQuotesAsync
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProspectQuotesAsync($prospect_id, $format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        return $this->getProspectQuotesAsyncWithHttpInfo($prospect_id, $format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProspectQuotesAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProspectQuotesAsyncWithHttpInfo($prospect_id, $format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        $returnType = '\Swagger\Client\Model\Quotes';
        $request = $this->getProspectQuotesRequest($prospect_id, $format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProspectQuotes'
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getProspectQuotesRequest($prospect_id, $format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        // verify the required parameter 'prospect_id' is set
        if ($prospect_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $prospect_id when calling getProspectQuotes'
            );
        }
        if (!preg_match("/^[a-z0-9]{24}$/", $prospect_id)) {
            throw new \InvalidArgumentException("invalid value for \"prospect_id\" when calling QuotesApi.getProspectQuotes, must conform to the pattern /^[a-z0-9]{24}$/.");
        }


        $resourcePath = '/prospect/{prospectId}/quotes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }
        // query params
        if ($created_before !== null) {
            $queryParams['createdBefore'] = ObjectSerializer::toQueryValue($created_before);
        }
        // query params
        if ($created_after !== null) {
            $queryParams['createdAfter'] = ObjectSerializer::toQueryValue($created_after);
        }
        // query params
        if ($accepted_before !== null) {
            $queryParams['acceptedBefore'] = ObjectSerializer::toQueryValue($accepted_before);
        }
        // query params
        if ($accepted_after !== null) {
            $queryParams['acceptedAfter'] = ObjectSerializer::toQueryValue($accepted_after);
        }
        // query params
        if ($rejected_before !== null) {
            $queryParams['rejectedBefore'] = ObjectSerializer::toQueryValue($rejected_before);
        }
        // query params
        if ($rejected_after !== null) {
            $queryParams['rejectedAfter'] = ObjectSerializer::toQueryValue($rejected_after);
        }

        // path params
        if ($prospect_id !== null) {
            $resourcePath = str_replace(
                '{' . 'prospectId' . '}',
                ObjectSerializer::toPathValue($prospect_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/csv', 'text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/csv', 'text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $queryParams['api-key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getQuoteById
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Quote
     */
    public function getQuoteById($prospect_id, $quote_id, $format = null)
    {
        list($response) = $this->getQuoteByIdWithHttpInfo($prospect_id, $quote_id, $format);
        return $response;
    }

    /**
     * Operation getQuoteByIdWithHttpInfo
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Quote, HTTP status code, HTTP response headers (array of strings)
     */
    public function getQuoteByIdWithHttpInfo($prospect_id, $quote_id, $format = null)
    {
        $returnType = '\Swagger\Client\Model\Quote';
        $request = $this->getQuoteByIdRequest($prospect_id, $quote_id, $format);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Quote',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getQuoteByIdAsync
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuoteByIdAsync($prospect_id, $quote_id, $format = null)
    {
        return $this->getQuoteByIdAsyncWithHttpInfo($prospect_id, $quote_id, $format)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getQuoteByIdAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuoteByIdAsyncWithHttpInfo($prospect_id, $quote_id, $format = null)
    {
        $returnType = '\Swagger\Client\Model\Quote';
        $request = $this->getQuoteByIdRequest($prospect_id, $quote_id, $format);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getQuoteById'
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getQuoteByIdRequest($prospect_id, $quote_id, $format = null)
    {
        // verify the required parameter 'prospect_id' is set
        if ($prospect_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $prospect_id when calling getQuoteById'
            );
        }
        if (!preg_match("/^[a-z0-9]{24}$/", $prospect_id)) {
            throw new \InvalidArgumentException("invalid value for \"prospect_id\" when calling QuotesApi.getQuoteById, must conform to the pattern /^[a-z0-9]{24}$/.");
        }

        // verify the required parameter 'quote_id' is set
        if ($quote_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $quote_id when calling getQuoteById'
            );
        }
        if (!preg_match("/^[a-z0-9]{24}$/", $quote_id)) {
            throw new \InvalidArgumentException("invalid value for \"quote_id\" when calling QuotesApi.getQuoteById, must conform to the pattern /^[a-z0-9]{24}$/.");
        }


        $resourcePath = '/prospect/{prospectId}/quote/{quoteId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }

        // path params
        if ($prospect_id !== null) {
            $resourcePath = str_replace(
                '{' . 'prospectId' . '}',
                ObjectSerializer::toPathValue($prospect_id),
                $resourcePath
            );
        }
        // path params
        if ($quote_id !== null) {
            $resourcePath = str_replace(
                '{' . 'quoteId' . '}',
                ObjectSerializer::toPathValue($quote_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/csv', 'text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/csv', 'text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $queryParams['api-key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getQuotes
     *
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Quotes
     */
    public function getQuotes($format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        list($response) = $this->getQuotesWithHttpInfo($format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after);
        return $response;
    }

    /**
     * Operation getQuotesWithHttpInfo
     *
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Quotes, HTTP status code, HTTP response headers (array of strings)
     */
    public function getQuotesWithHttpInfo($format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        $returnType = '\Swagger\Client\Model\Quotes';
        $request = $this->getQuotesRequest($format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Quotes',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getQuotesAsync
     *
     * 
     *
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuotesAsync($format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        return $this->getQuotesAsyncWithHttpInfo($format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getQuotesAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuotesAsyncWithHttpInfo($format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {
        $returnType = '\Swagger\Client\Model\Quotes';
        $request = $this->getQuotesRequest($format, $status, $created_before, $created_after, $accepted_before, $accepted_after, $rejected_before, $rejected_after);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getQuotes'
     *
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     * @param  string $status The status to filter (optional)
     * @param  \DateTime $created_before The start date to filter quotes by their creation date (optional)
     * @param  \DateTime $created_after The end date to filter quotes by their creation date (optional)
     * @param  \DateTime $accepted_before The start date to filter quotes by their accepted date (optional)
     * @param  \DateTime $accepted_after The end date to filter quotes by their accepted date (optional)
     * @param  \DateTime $rejected_before The start date to filter quotes by their rejected date (optional)
     * @param  \DateTime $rejected_after The end date to filter quotes by their rejected date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getQuotesRequest($format = null, $status = null, $created_before = null, $created_after = null, $accepted_before = null, $accepted_after = null, $rejected_before = null, $rejected_after = null)
    {

        $resourcePath = '/prospects/quotes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }
        // query params
        if ($created_before !== null) {
            $queryParams['createdBefore'] = ObjectSerializer::toQueryValue($created_before);
        }
        // query params
        if ($created_after !== null) {
            $queryParams['createdAfter'] = ObjectSerializer::toQueryValue($created_after);
        }
        // query params
        if ($accepted_before !== null) {
            $queryParams['acceptedBefore'] = ObjectSerializer::toQueryValue($accepted_before);
        }
        // query params
        if ($accepted_after !== null) {
            $queryParams['acceptedAfter'] = ObjectSerializer::toQueryValue($accepted_after);
        }
        // query params
        if ($rejected_before !== null) {
            $queryParams['rejectedBefore'] = ObjectSerializer::toQueryValue($rejected_before);
        }
        // query params
        if ($rejected_after !== null) {
            $queryParams['rejectedAfter'] = ObjectSerializer::toQueryValue($rejected_after);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/csv', 'text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/csv', 'text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $queryParams['api-key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation newProspectQuote
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  \Swagger\Client\Model\NewQuote $quote quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Quote
     */
    public function newProspectQuote($prospect_id, $quote, $format = null)
    {
        list($response) = $this->newProspectQuoteWithHttpInfo($prospect_id, $quote, $format);
        return $response;
    }

    /**
     * Operation newProspectQuoteWithHttpInfo
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  \Swagger\Client\Model\NewQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Quote, HTTP status code, HTTP response headers (array of strings)
     */
    public function newProspectQuoteWithHttpInfo($prospect_id, $quote, $format = null)
    {
        $returnType = '\Swagger\Client\Model\Quote';
        $request = $this->newProspectQuoteRequest($prospect_id, $quote, $format);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Quote',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation newProspectQuoteAsync
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  \Swagger\Client\Model\NewQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function newProspectQuoteAsync($prospect_id, $quote, $format = null)
    {
        return $this->newProspectQuoteAsyncWithHttpInfo($prospect_id, $quote, $format)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation newProspectQuoteAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  \Swagger\Client\Model\NewQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function newProspectQuoteAsyncWithHttpInfo($prospect_id, $quote, $format = null)
    {
        $returnType = '\Swagger\Client\Model\Quote';
        $request = $this->newProspectQuoteRequest($prospect_id, $quote, $format);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'newProspectQuote'
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  \Swagger\Client\Model\NewQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function newProspectQuoteRequest($prospect_id, $quote, $format = null)
    {
        // verify the required parameter 'prospect_id' is set
        if ($prospect_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $prospect_id when calling newProspectQuote'
            );
        }
        if (!preg_match("/^[a-z0-9]{24}$/", $prospect_id)) {
            throw new \InvalidArgumentException("invalid value for \"prospect_id\" when calling QuotesApi.newProspectQuote, must conform to the pattern /^[a-z0-9]{24}$/.");
        }

        // verify the required parameter 'quote' is set
        if ($quote === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $quote when calling newProspectQuote'
            );
        }

        $resourcePath = '/prospect/{prospectId}/quotes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }

        // path params
        if ($prospect_id !== null) {
            $resourcePath = str_replace(
                '{' . 'prospectId' . '}',
                ObjectSerializer::toPathValue($prospect_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($quote)) {
            $_tempBody = $quote;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/csv', 'text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/csv', 'text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $queryParams['api-key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateProspectQuote
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  \Swagger\Client\Model\UpdateQuote $quote quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Quote
     */
    public function updateProspectQuote($prospect_id, $quote_id, $quote, $format = null)
    {
        list($response) = $this->updateProspectQuoteWithHttpInfo($prospect_id, $quote_id, $quote, $format);
        return $response;
    }

    /**
     * Operation updateProspectQuoteWithHttpInfo
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  \Swagger\Client\Model\UpdateQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Quote, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateProspectQuoteWithHttpInfo($prospect_id, $quote_id, $quote, $format = null)
    {
        $returnType = '\Swagger\Client\Model\Quote';
        $request = $this->updateProspectQuoteRequest($prospect_id, $quote_id, $quote, $format);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Quote',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateProspectQuoteAsync
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  \Swagger\Client\Model\UpdateQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProspectQuoteAsync($prospect_id, $quote_id, $quote, $format = null)
    {
        return $this->updateProspectQuoteAsyncWithHttpInfo($prospect_id, $quote_id, $quote, $format)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateProspectQuoteAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  \Swagger\Client\Model\UpdateQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProspectQuoteAsyncWithHttpInfo($prospect_id, $quote_id, $quote, $format = null)
    {
        $returnType = '\Swagger\Client\Model\Quote';
        $request = $this->updateProspectQuoteRequest($prospect_id, $quote_id, $quote, $format);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateProspectQuote'
     *
     * @param  string $prospect_id The id of the prospect (required)
     * @param  string $quote_id The id of the quote (required)
     * @param  \Swagger\Client\Model\UpdateQuote $quote (required)
     * @param  string $format An optional flag to force a response format. Note that the API also supports content negotiation and honors the Accept header. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateProspectQuoteRequest($prospect_id, $quote_id, $quote, $format = null)
    {
        // verify the required parameter 'prospect_id' is set
        if ($prospect_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $prospect_id when calling updateProspectQuote'
            );
        }
        if (!preg_match("/^[a-z0-9]{24}$/", $prospect_id)) {
            throw new \InvalidArgumentException("invalid value for \"prospect_id\" when calling QuotesApi.updateProspectQuote, must conform to the pattern /^[a-z0-9]{24}$/.");
        }

        // verify the required parameter 'quote_id' is set
        if ($quote_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $quote_id when calling updateProspectQuote'
            );
        }
        if (!preg_match("/^[a-z0-9]{24}$/", $quote_id)) {
            throw new \InvalidArgumentException("invalid value for \"quote_id\" when calling QuotesApi.updateProspectQuote, must conform to the pattern /^[a-z0-9]{24}$/.");
        }

        // verify the required parameter 'quote' is set
        if ($quote === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $quote when calling updateProspectQuote'
            );
        }

        $resourcePath = '/prospect/{prospectId}/quote/{quoteId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }

        // path params
        if ($prospect_id !== null) {
            $resourcePath = str_replace(
                '{' . 'prospectId' . '}',
                ObjectSerializer::toPathValue($prospect_id),
                $resourcePath
            );
        }
        // path params
        if ($quote_id !== null) {
            $resourcePath = str_replace(
                '{' . 'quoteId' . '}',
                ObjectSerializer::toPathValue($quote_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($quote)) {
            $_tempBody = $quote;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/csv', 'text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/csv', 'text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $queryParams['api-key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
