=begin
#Sirena API

#Sirena API for lead providers and prospect data manipulation

OpenAPI spec version: 1.5.0
Contact: it@getsirena.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/agent'
require 'swagger_client/models/categories'
require 'swagger_client/models/categories_by_industry'
require 'swagger_client/models/category'
require 'swagger_client/models/defaults'
require 'swagger_client/models/error'
require 'swagger_client/models/finance'
require 'swagger_client/models/interaction'
require 'swagger_client/models/interaction_medium'
require 'swagger_client/models/interaction_output'
require 'swagger_client/models/interaction_output_conversations'
require 'swagger_client/models/interactions'
require 'swagger_client/models/lead'
require 'swagger_client/models/lead_data'
require 'swagger_client/models/message_medium'
require 'swagger_client/models/message_output'
require 'swagger_client/models/money_amount'
require 'swagger_client/models/money_amount_estimate'
require 'swagger_client/models/new_quote'
require 'swagger_client/models/new_subscription'
require 'swagger_client/models/object_id'
require 'swagger_client/models/odometer'
require 'swagger_client/models/product'
require 'swagger_client/models/proposal'
require 'swagger_client/models/proposal_items'
require 'swagger_client/models/prospect'
require 'swagger_client/models/prospects'
require 'swagger_client/models/quote'
require 'swagger_client/models/quote_item'
require 'swagger_client/models/quotes'
require 'swagger_client/models/real_estate_product'
require 'swagger_client/models/subscription'
require 'swagger_client/models/subscriptions'
require 'swagger_client/models/topic'
require 'swagger_client/models/topics'
require 'swagger_client/models/update_quote'
require 'swagger_client/models/general_lead'
require 'swagger_client/models/real_estate_lead'
require 'swagger_client/models/retail_lead'
require 'swagger_client/models/saving_plan_lead'
require 'swagger_client/models/saving_plan_product'
require 'swagger_client/models/vehicle_lead'
require 'swagger_client/models/vehicle_product'

# APIs
require 'swagger_client/api/default_api'
require 'swagger_client/api/interactions_api'
require 'swagger_client/api/leads_api'
require 'swagger_client/api/notifications_api'
require 'swagger_client/api/prospects_api'
require 'swagger_client/api/quotes_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
