<?php
/**
 * InteractionOutputConversationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers and prospect data manipulation
 *
 * OpenAPI spec version: 1.5.0
 * Contact: it@getsirena.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InteractionOutputConversationsTest Class Doc Comment
 *
 * @category    Class */
// * @description InteractionOutputConversations
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InteractionOutputConversationsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InteractionOutputConversations"
     */
    public function testInteractionOutputConversations()
    {
    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "provider_name"
     */
    public function testPropertyProviderName()
    {
    }

    /**
     * Test attribute "thread_title"
     */
    public function testPropertyThreadTitle()
    {
    }

    /**
     * Test attribute "thread_subtitle"
     */
    public function testPropertyThreadSubtitle()
    {
    }

    /**
     * Test attribute "thread_thumbnail"
     */
    public function testPropertyThreadThumbnail()
    {
    }
}
