<?php
/**
 * VehicleProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers and prospect data manipulation
 *
 * OpenAPI spec version: 1.5.0
 * Contact: it@getsirena.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VehicleProductTest Class Doc Comment
 *
 * @category    Class */
// * @description VehicleProduct
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VehicleProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VehicleProduct"
     */
    public function testVehicleProduct()
    {
    }

    /**
     * Test attribute "make"
     */
    public function testPropertyMake()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "detail"
     */
    public function testPropertyDetail()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "model_year"
     */
    public function testPropertyModelYear()
    {
    }

    /**
     * Test attribute "production_year"
     */
    public function testPropertyProductionYear()
    {
    }

    /**
     * Test attribute "trim_level"
     */
    public function testPropertyTrimLevel()
    {
    }

    /**
     * Test attribute "style"
     */
    public function testPropertyStyle()
    {
    }

    /**
     * Test attribute "fuel_type"
     */
    public function testPropertyFuelType()
    {
    }

    /**
     * Test attribute "vim"
     */
    public function testPropertyVim()
    {
    }

    /**
     * Test attribute "registration_plate"
     */
    public function testPropertyRegistrationPlate()
    {
    }

    /**
     * Test attribute "odometer"
     */
    public function testPropertyOdometer()
    {
    }

    /**
     * Test attribute "trade_in_vehicle"
     */
    public function testPropertyTradeInVehicle()
    {
    }

    /**
     * Test attribute "finance"
     */
    public function testPropertyFinance()
    {
    }
}
