<?php
/**
 * LeadsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirena API
 *
 * Sirena API for lead providers and prospect data manipulation
 *
 * OpenAPI spec version: 1.5.0
 * Contact: it@getsirena.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LeadsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LeadsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCategories
     *
     * .
     *
     */
    public function testGetCategories()
    {
    }

    /**
     * Test case for getDefaults
     *
     * .
     *
     */
    public function testGetDefaults()
    {
    }

    /**
     * Test case for newInsuranceLead
     *
     * .
     *
     */
    public function testNewInsuranceLead()
    {
    }

    /**
     * Test case for newRetailLead
     *
     * .
     *
     */
    public function testNewRetailLead()
    {
    }

    /**
     * Test case for newSavingPlanLead
     *
     * .
     *
     */
    public function testNewSavingPlanLead()
    {
    }

    /**
     * Test case for newVehicleLead
     *
     * .
     *
     */
    public function testNewVehicleLead()
    {
    }
}
